"""Пакет эвристик по тексту вопроса (модель, тема, код ошибки)."""
from __future__ import annotations

# --- _base ---
from app.bot.heuristics._base import (
    _PRINTER_MENTION_RE,
    _ace_mentioned,
    _extract_error_code,
    _has_geo_social_cues,
    _is_error_code_query,
    _mentions_competitor_printer,
    _model_slug_hints,
    _printer_mentioned,
    _user_already_replaced_motherboard,
)

# --- _error_codes ---
from app.bot.heuristics._error_codes import (
    _error_code_candidates,
    _error_code_target_suffix,
    _error_code_variant_suffix,
    _pick_error_code_doc,
)

# --- _ace ---
from app.bot.heuristics._ace import (
    _is_ace_unit_trade_banter,
    _is_ace_unit_price_shopping_chatter,
    _is_combo_ace_marketplace_chat,
    _topic_is_ace_connection_intent,
    _topic_is_ace_filament_drying_intent,
    _topic_is_ace_filament_slot_intent,
    _topic_is_ace_not_detected_intent,
)

# --- _banter ---
from app.bot.heuristics._banter import (
    _COLOQUIAL_KAK_RE,
    _DEFER_TO_EXPERT_RE,
    _MARKETPLACE_HOST_RE,
    _PEER_ACTION_PAST_RE,
    _PEER_PAST_PARAM_NOUN_RE,
    _PEER_PAST_QUERY_RE,
    _is_ace_chitu_hardware_observation,
    _is_bare_competitor_printer_question,
    _is_bare_rhetorical_context_question,
    _is_casual_advice_in_thread,
    _is_chat_meta_discussion,
    _is_chat_past_incident_recollection,
    _is_colloquial_printer_fragment,
    _is_competitor_showcase_request,
    _is_conversational_skepticism,
    _is_cross_chat_tip_sharing,
    _is_design_feature_car_sarcasm,
    _is_expert_deferral_chatter,
    _is_filament_brand_quality_opinion,
    _is_filament_feed_test_probe,
    _is_filament_testing_plan_sharing,
    _is_filament_tolerance_banter,
    _is_first_days_experience_sharing,
    _is_hardware_vs_settings_dilemma,
    _is_joke_printer_model_clarify_reply,
    _is_layer_profile_thread_opinion,
    _is_marketplace_promo_message,
    _is_material_strength_discussion,
    _is_money_worth_banter,
    _is_multicolor_experience_opinion,
    _is_multicolor_flow_calibration_chat,
    _is_multicolor_preset_banter,
    _is_multicolor_tower_rhetoric,
    _is_offbeat_social_banter,
    _is_offtopic_work_life_sidebar,
    _is_offtopic_auto_sidebar,
    _is_other_printer_experience_story,
    _is_other_printer_maintenance_story,
    _is_partial_manual_find_observation,
    _is_peer_action_experience_question,
    _is_peer_claim_debate_relay,
    _is_peer_diagnostic_interrogation,
    _is_peer_social_printer_question,
    _is_personal_chat_action_reference,
    _is_price_hyperbole_banter,
    _is_price_negotiation_chatter,
    _is_print_quality_meta_curiosity,
    _is_print_task_planning_statement,
    _is_printer_comparison_opinion,
    _is_printer_purchase_material_opinion,
    _is_printing_status_announcement,
    _is_problem_combo_banter,
    _is_product_news_announcement,
    _is_purchase_deliberation_banter,
    _is_pure_numeric_or_symbol_message,
    _is_relay_to_peer_chatter,
    _is_sarcastic_printer_banter,
    _is_sarcastic_thread_banter,
    _is_slicer_app_disambiguation,
    _is_technical_observation_sharing,
    _is_technical_opinion_sharing,
    _is_third_party_filament_brand_chat,
    _is_thread_printing_tip,
    _is_unrelated_pc_hardware_banter,
    _is_vague_filament_thread_reference,
    _is_profanity_outburst_chatter,
    _is_works_fine_reassurance,
    _is_marketplace_search_chatter,
    _is_peer_diagnostic_checklist,
    _is_bare_combo_variant_fragment,
    _is_social_location_question,
    _is_content_post_request,
    _is_thread_continuation_filler,
    _is_competitor_model_disambiguation,
    _is_slicer_preview_chatter,
    _is_personal_opinion_remark,
    _is_photo_observation_musing,
    _is_bare_fragment_question,
    _is_community_experience_poll,
    _is_private_money_contact_spam,
    _is_firmware_slicer_version_gossip,
    _is_offtopic_news_or_shop_meta,
    _is_thread_humor_meme,
    _is_filament_brand_social_chat,
    _is_figurative_mood_remark,
    _is_general_thread_sidebar,
    _is_peer_calibration_reply_chatter,
    _is_thread_bed_surface_opinion,
    _is_bot_helper_appreciation_meta,
    _is_vague_fix_without_symptom,
    _message_has_help_intent,
)

# --- _intents ---
from app.bot.heuristics._intents import (
    _topic_is_filament_bed_removal_intent,
    _topic_is_filament_feed_intent,
    _topic_is_filament_material_choice_intent,
    _topic_is_filament_slicing_settings_intent,
    _topic_is_firmware_update_intent,
    _topic_is_marketplace_commerce_intent,
    _topic_is_multicolor_firmware_intent,
    _topic_is_resonance_pa_tuning_intent,
    _topic_is_slicer_choice_opinion_intent,
    _topic_is_slicer_feature_help_intent,
    _topic_is_slicer_vertical_hole_intent,
    _topic_needs_printer_model,
)

# --- _filter ---
from app.bot.heuristics._filter import (
    _is_conversational_chatter,
    _is_generic_help_without_context,
    _is_geo_social_only_request,
    _is_non_wiki_chatter_message,
    _needs_model_clarification,
)

__all__ = [
    # _base
    "_PRINTER_MENTION_RE",
    "_ace_mentioned",
    "_extract_error_code",
    "_has_geo_social_cues",
    "_is_error_code_query",
    "_mentions_competitor_printer",
    "_model_slug_hints",
    "_printer_mentioned",
    "_user_already_replaced_motherboard",
    # _error_codes
    "_error_code_candidates",
    "_error_code_target_suffix",
    "_error_code_variant_suffix",
    "_pick_error_code_doc",
    # _ace
    "_is_ace_unit_trade_banter",
    "_is_ace_unit_price_shopping_chatter",
    "_is_combo_ace_marketplace_chat",
    "_topic_is_ace_connection_intent",
    "_topic_is_ace_filament_drying_intent",
    "_topic_is_ace_filament_slot_intent",
    "_topic_is_ace_not_detected_intent",
    # _banter
    "_COLOQUIAL_KAK_RE",
    "_DEFER_TO_EXPERT_RE",
    "_MARKETPLACE_HOST_RE",
    "_PEER_ACTION_PAST_RE",
    "_PEER_PAST_PARAM_NOUN_RE",
    "_PEER_PAST_QUERY_RE",
    "_is_ace_chitu_hardware_observation",
    "_is_bare_competitor_printer_question",
    "_is_bare_rhetorical_context_question",
    "_is_casual_advice_in_thread",
    "_is_chat_meta_discussion",
    "_is_chat_past_incident_recollection",
    "_is_colloquial_printer_fragment",
    "_is_competitor_showcase_request",
    "_is_conversational_skepticism",
    "_is_cross_chat_tip_sharing",
    "_is_design_feature_car_sarcasm",
    "_is_expert_deferral_chatter",
    "_is_filament_brand_quality_opinion",
    "_is_filament_feed_test_probe",
    "_is_filament_testing_plan_sharing",
    "_is_filament_tolerance_banter",
    "_is_first_days_experience_sharing",
    "_is_hardware_vs_settings_dilemma",
    "_is_joke_printer_model_clarify_reply",
    "_is_layer_profile_thread_opinion",
    "_is_marketplace_promo_message",
    "_is_material_strength_discussion",
    "_is_money_worth_banter",
    "_is_multicolor_experience_opinion",
    "_is_multicolor_flow_calibration_chat",
    "_is_multicolor_preset_banter",
    "_is_multicolor_tower_rhetoric",
    "_is_offbeat_social_banter",
    "_is_other_printer_experience_story",
    "_is_other_printer_maintenance_story",
    "_is_partial_manual_find_observation",
    "_is_peer_action_experience_question",
    "_is_peer_claim_debate_relay",
    "_is_peer_diagnostic_interrogation",
    "_is_peer_social_printer_question",
    "_is_personal_chat_action_reference",
    "_is_price_hyperbole_banter",
    "_is_price_negotiation_chatter",
    "_is_print_quality_meta_curiosity",
    "_is_print_task_planning_statement",
    "_is_printer_comparison_opinion",
    "_is_printer_purchase_material_opinion",
    "_is_printing_status_announcement",
    "_is_problem_combo_banter",
    "_is_product_news_announcement",
    "_is_purchase_deliberation_banter",
    "_is_pure_numeric_or_symbol_message",
    "_is_relay_to_peer_chatter",
    "_is_sarcastic_printer_banter",
    "_is_sarcastic_thread_banter",
    "_is_slicer_app_disambiguation",
    "_is_technical_observation_sharing",
    "_is_technical_opinion_sharing",
    "_is_third_party_filament_brand_chat",
    "_is_thread_printing_tip",
    "_is_unrelated_pc_hardware_banter",
    "_is_vague_filament_thread_reference",
    "_is_profanity_outburst_chatter",
    "_is_works_fine_reassurance",
    "_is_marketplace_search_chatter",
    "_is_peer_diagnostic_checklist",
    "_is_bare_combo_variant_fragment",
    "_is_social_location_question",
    "_is_content_post_request",
    "_is_thread_continuation_filler",
    "_is_competitor_model_disambiguation",
    "_is_slicer_preview_chatter",
    "_is_personal_opinion_remark",
    "_is_photo_observation_musing",
    "_is_bare_fragment_question",
    "_message_has_help_intent",
    # _intents
    "_topic_is_filament_bed_removal_intent",
    "_topic_is_filament_feed_intent",
    "_topic_is_filament_material_choice_intent",
    "_topic_is_filament_slicing_settings_intent",
    "_topic_is_firmware_update_intent",
    "_topic_is_marketplace_commerce_intent",
    "_topic_is_multicolor_firmware_intent",
    "_topic_is_resonance_pa_tuning_intent",
    "_topic_is_slicer_choice_opinion_intent",
    "_topic_is_slicer_feature_help_intent",
    "_topic_is_slicer_vertical_hole_intent",
    "_topic_needs_printer_model",
    # _filter
    "_is_conversational_chatter",
    "_is_generic_help_without_context",
    "_is_geo_social_only_request",
    "_is_non_wiki_chatter_message",
    "_needs_model_clarification",
]
