name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
categories:
  - title: Features
    when:
      labels:
        - enhancement
        - feature
  - title: Bug fixes
    when:
      labels:
        - bug
        - fix
  - title: Bot
    when:
      label: bot
  - title: Dependencies
    when:
      label: dependencies
  - title: Maintenance
    when:
      labels:
        - ci
        - chore
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
no-changes-template: "Нет изменений в этой версии."
template: |
  ## Изменения

  $CHANGES
