name: Markdown links

on:
  push:
    branches: [master]
    paths:
      - "**/*.md"
  pull_request:
    branches: [master]
    paths:
      - "**/*.md"

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: yes
          config-file: .github/markdown-link-check-config.json
